"""
Multi-Format Report Generator & Reproducibility Engine for DataLens AI
Exports analysis into PDF, Markdown, and JSON formats.
"""

import json
import hashlib
import datetime
from typing import Dict, Any, Optional
import pandas as pd
from fpdf import FPDF
from .logger import app_logger


class PDFReport(FPDF):
    """Custom styled PDF document for DataLens AI Reports."""

    def header(self):
        self.set_font("Helvetica", "B", 14)
        self.set_text_color(30, 41, 59)
        self.cell(0, 8, "DATALENS AI - EXECUTIVE AUDIT REPORT", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(100, 116, 139)
        self.cell(0, 4, "Grounded Intelligence & Data Quality Verification", border=False, align="C", new_x="LMARGIN", new_y="NEXT")
        self.ln(4)

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(148, 163, 184)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by DataLens AI Studio", align="C")


class ReportGenerator:
    """
    Generates downloadable reports in PDF, Markdown, and JSON format with full audit reproducibility.
    """

    @classmethod
    def generate_pdf_report(
        cls,
        dataset_name: str,
        df: pd.DataFrame,
        profiler_dict: Dict[str, Any],
        quality_dict: Dict[str, Any],
        stats_dict: Dict[str, Any],
        ai_briefing: str,
        privacy_dict: Optional[Dict[str, Any]] = None,
    ) -> bytes:
        """Generates an executive PDF report and returns raw bytes."""
        pdf = PDFReport(orientation="P", unit="mm", format="A4")
        pdf.set_auto_page_break(auto=True, margin=15)
        pdf.add_page()

        # Metadata banner
        pdf.set_fill_color(241, 245, 249)
        pdf.set_font("Helvetica", "B", 10)
        pdf.set_text_color(30, 41, 59)
        now_str = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
        pdf.cell(0, 7, f" Dataset: {dataset_name}  |  Date: {now_str}  |  Health Score: {quality_dict.get('health_score')}/100", fill=True, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(3)

        # 1. Dataset Dimensions & Privacy
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(59, 130, 246)
        pdf.cell(pdf.epw, 6, "1. DATASET OVERVIEW & PRIVACY SCAN", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)

        priv_score = privacy_dict.get("privacy_safety_score", 100) if privacy_dict else 100
        overview_text = (
            f"Total Records: {profiler_dict.get('total_rows')}  |  Features: {profiler_dict.get('total_cols')}  |  "
            f"Memory: {profiler_dict.get('memory_mb')} MB  |  Privacy Safety: {priv_score}/100\n"
            f"Column Types: {profiler_dict.get('type_counts')}"
        )
        pdf.multi_cell(pdf.epw, 5, overview_text, new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # 2. Data Quality & Anomalies
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(59, 130, 246)
        pdf.cell(pdf.epw, 6, "2. DATA QUALITY & ANOMALIES", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)

        qual_text = (
            f"Duplicate Rows: {quality_dict.get('duplicate_rows')} ({quality_dict.get('duplicate_pct')}%)\n"
            f"Missing Cells: {quality_dict.get('total_missing_cells')} ({profiler_dict.get('missing_cells_pct')}%)"
        )
        pdf.multi_cell(pdf.epw, 5, qual_text, new_x="LMARGIN", new_y="NEXT")

        outliers = quality_dict.get("outliers", {})
        if outliers:
            out_lines = [f" - {c}: {info['iqr']['outlier_count']} IQR outliers (Bounds: [{info['iqr']['lower_bound']}, {info['iqr']['upper_bound']}])" for c, info in outliers.items() if info["iqr"]["outlier_count"] > 0]
            if out_lines:
                pdf.multi_cell(pdf.epw, 5, "\n".join(out_lines), new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # 3. Statistical Summary
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(59, 130, 246)
        pdf.cell(pdf.epw, 6, "3. KEY STATISTICAL HIGHLIGHTS", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)

        num_stats = stats_dict.get("numerical", {})
        stat_lines = []
        for col, s in list(num_stats.items())[:5]:
            stat_lines.append(f" - {col}: Mean={s.get('mean')}, Median={s.get('median_50')}, Std={s.get('std')}, Skew={s.get('skewness')}")
        pdf.multi_cell(pdf.epw, 5, "\n".join(stat_lines) if stat_lines else "No numerical features found.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # 4. Correlations
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(59, 130, 246)
        pdf.cell(pdf.epw, 6, "4. SIGNIFICANT CORRELATIONS", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.set_text_color(51, 65, 85)

        corrs = stats_dict.get("correlations", {}).get("strong_correlations", [])
        if corrs:
            corr_lines = [f" - {c['col1']} <-> {c['col2']}: Pearson r = {c['pearson']} ({c['strength']} {c['direction']})" for c in corrs[:4]]
            pdf.multi_cell(pdf.epw, 5, "\n".join(corr_lines), new_x="LMARGIN", new_y="NEXT")
        else:
            pdf.multi_cell(pdf.epw, 5, "No strong pairwise correlations detected.", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(2)

        # 5. Executive AI Briefing
        pdf.set_font("Helvetica", "B", 11)
        pdf.set_text_color(59, 130, 246)
        pdf.cell(pdf.epw, 6, "5. GROUNDED EXECUTIVE AI BRIEFING", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8.5)
        pdf.set_text_color(51, 65, 85)
        clean_briefing = ai_briefing.replace("#", "").replace("**", "").replace("*", "").encode('latin-1', 'replace').decode('latin-1')
        pdf.multi_cell(pdf.epw, 4.5, clean_briefing, new_x="LMARGIN", new_y="NEXT")

        app_logger.info("PDF report compiled successfully.")
        return bytes(pdf.output())

    @classmethod
    def generate_reproducibility_json(
        cls,
        dataset_name: str,
        df: pd.DataFrame,
        profiler_dict: Dict[str, Any],
        quality_dict: Dict[str, Any],
        stats_dict: Dict[str, Any],
        cleaning_log: Optional[Dict[str, Any]] = None,
        ml_results: Optional[Dict[str, Any]] = None,
    ) -> str:
        """Creates a timestamped, cryptographically checksummed JSON audit artifact."""
        # Calculate dataset SHA-256
        df_bytes = df.to_csv(index=False).encode("utf-8")
        data_hash = hashlib.sha256(df_bytes).hexdigest()

        audit = {
            "metadata": {
                "dataset_name": dataset_name,
                "timestamp_utc": datetime.datetime.now(datetime.timezone.utc).isoformat(),
                "sha256_checksum": data_hash,
                "platform": "DataLens AI v1.0",
            },
            "profile": profiler_dict,
            "quality": quality_dict,
            "statistics": stats_dict,
            "cleaning_history": cleaning_log or {},
            "machine_learning": {
                k: v for k, v in (ml_results or {}).items() if not str(k).startswith("fig_")
            },
        }

        app_logger.info("Reproducibility JSON audit generated.")
        return json.dumps(audit, indent=2, default=str)
